services:
  - type: web
    name: bioorbit-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend
    startCommand: npm start
    buildCommand: npm install
    # Habilitar WebSocket no Render
    autoDeploy: true
    # Configuração para permitir conexões WebSocket
    headers:
      - path: /*
        name: Connection
        value: Upgrade
      - path: /*
        name: Upgrade
        value: websocket
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://gustavodeazevedo2003:EliseteDaniKa4@biocalib.ybbb3or.mongodb.net/?retryWrites=true&w=majority&appName=biocalib
      - key: JWT_SECRET
        generateValue: true
      - key: CORPORATE_TOKEN
        value: BioKeyOne
      - key: FRONTEND_URL
        value: https://bio-orbit.vercel.app
    healthCheckPath: /health
