services:
  - type: web
    name: bioorbit-backend
    env: node
    region: oregon
    plan: free
    startCommand: npm start    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://gustavodeazevedo2003:EliseteDaniKa4@biocalib.ybbb3or.mongodb.net/?retryWrites=true&w=majority&appName=biocalib
      - key: JWT_SECRET
        generateValue: true
      - key: CORPORATE_TOKEN
        value: BioKeyOne
    healthCheckPath: /
