services:
  - type: web
    name: bioorbit-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run install-backend
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: CORPORATE_TOKEN
        value: BioKeyOne
    healthCheckPath: /
