services:
  - type: web
    name: bioorbit-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install
    startCommand: npm start
    rootDir: ./backend
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: bioorbit-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
    healthCheckPath: /
