services:
  - type: web
    name: bioorbit-backend
    env: node
    region: oregon
    plan: free
    rootDir: backend
    startCommand: npm start
    buildCommand: npm install
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://gustavodeazevedo2003:EliseteDaniKa4@biocalib.ybbb3or.mongodb.net/?retryWrites=true&w=majority&appName=biocalib
      - key: JWT_SECRET
        generateValue: true
      - key: CORPORATE_TOKEN
        value: BioKeyOne
      - key: RESEND_API_KEY
        value: re_3GG6rh3J_23meGpp6kNMNsy1p8TweB1V8
      - key: RESEND_FROM_EMAIL
        value: bioorbit@resend.dev
      - key: FRONTEND_URL
        value: https://bio-orbit.vercel.app
    healthCheckPath: /health
