services:
  - type: web
    name: bioorbit-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm run install-backend
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        fromDatabase:
          name: bioorbit-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORPORATE_TOKEN
        value: BioKeyOne
    healthCheckPath: /
